name: Update Azure Block IP Feed

permissions:
  contents: write

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:       # Allows manual run in the GitHub UI

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run resolver script
        run: python resolve_to_ips.py

      - name: Commit and push changes
        run: |
          git config --global user.email "beslinnikola@gmail.com"
          git config --global user.name "IT3ngineer"
          git add AzureBlockListIPs.txt
          git commit -m "Auto-update Azure IP feed" || echo "No changes to commit"
          git push
